### ISSUE TITLE
Extracting owned cards

### ISSUE THREAD

**Issue by xmichaelx** [Sembiance/hearthstonejson#3]
Hello, does hearthstonejson allows for extracting only card names owned by player (is such info present in files stored on my computer)? Suppose I would like to make a copy of my library in json.

**Comment by Sembiance** [comment]
Sorry, I am not aware of any way to do this. It is unlikely that the list of cards you own are kept on your computer. They are likely sent to the client over the network whenever you first connect or when the collection is opened or at some other time. It would be possible to extract this information from the network stream but it is outside the scope of hearthstonejson.
