### ISSUE TITLE
Can't generate json file

### ISSUE THREAD

**Issue by geft** [Sembiance/hearthstonejson#4]
I've got the following error

```
geft@ubuntu:~/hearthstonejson$ sudo node generate.js base-Win.MPQ 
Clearing 'out' directory...
Extracting MPQ...
RUNNING: /home/geft/hearthstonejson/MPQExtractor/build/bin/MPQExtractor -e Data\Win\cardxml0.unity3d -f -o /home/geft/hearthstonejson/out base-Win.MPQ
Extracting card XML...
Processing card languages...
Processing language: enUS
Error for file: /home/geft/hearthstonejson/out/cardxml0/TextAsset/enUS.txt
Error: ENOENT, open '/home/geft/hearthstonejson/out/cardxml0/TextAsset/enUS.txt'
Error: ENOENT, open '/home/geft/hearthstonejson/out/cardxml0/TextAsset/enUS.txt'

**Comment by Sembiance** [comment]
Hello

Yes, I MPQ files have changed since I last generated the data and are now
broken. On windows though you can find the cardxml0.data file or something
along those lines and point at that file instead.

I'm traveling right now so can't get more specific. I can help ore once I
return home and look at files and try the code out. Should be home tomorrow
:)

**Comment by geft** [comment]
Ah, I see. Does that mean the json file will be updated tomorrow? On the
website it says April 9.

**Comment by Sembiance** [comment]
Yup, plan on updating it later today.

**Comment by geft** [comment]
Awesome! Thanks for the hard work.

**Comment by vayzor** [comment]
Been looking into this for a whole day until I saw that the all the paths in the MPQ had changed T.T
I'm not much of a linux user so I had a bad time understanding the generation files.
Anyways, I'd like to thank you for this and your website. I'm using your json on every updates for my android app https://play.google.com/store/apps/details?id=net.hearthbase.android.hearthbase.
Just wanted to let you know your work is very useful to a lot of people !

**Comment by Sembiance** [comment]
Hello

I have updated hearthstonejson.com with the latest data. Enjoy :)

**Comment by vayzor** [comment]
Thank you very much ! :)

**Comment by burythehammer** [comment]
Very useful, with all the blackrock cards. Thanks.
