### ISSUE TITLE
Question about enumIDs and names

### ISSUE THREAD

**Issue by rithms** [Sembiance/hearthstonejson#5]
Out of curiosity,
Where did you get the names associated with the enumIDs from the XML data?

i.e. - 
var ENUMID_TO_NAME =
{
	185 : "CardName",
	183 : "CardSet",
	202 : "CardType",
	201 : "Faction",
	199 : "Class",
	203 : "Rarity",
	48 : "Cost",
	251 : "AttackVisualType",
	184 : "CardTextInHand",
	47 : "Atk",
	45 : "Health",
	321 : "Collectible",
        etc.
}

Extracting the files using disunity doesn't show this information for me. Did you just have to manually figure it out and map them?

**Comment by Sembiance** [comment]
They were manually entered by me.

I used HearthHead.com for reference and guessed where info there wasn't available.

I too could not find this anywhere in the files extracted by disunity.
